BI-2536: Fix integration/module tests on windows. Fix a significant portion of e2e tests (#298)

diff --git a/.evg.yml b/.evg.yml
--- a/.evg.yml
+++ b/.evg.yml
@@ -386,6 +386,12 @@ functions:
         ${PREPARE_SHELL}
         set -o errexit
         make ${var_target}
+
+        # On Windows we need to kill mongod after the tests run or the shell scripts
+        # never terminate. This is likely due to some unflushed I/O.
+        if [ "${_variant}" = windows ]; then
+            taskkill /F /im mongod.exe || true
+        fi
         [ -z "${_race_detector}" ] || ${SCRIPT_DIR}/check-races.sh
 
   "run unit benchmarks":
@@ -397,6 +403,11 @@ functions:
         export PACKAGE='${var_package}'
         set -o errexit
         ${SCRIPT_DIR}/run-unit-benchmarks.sh
+        # On Windows we need to kill mongod after the tests run or the shell scripts
+        # never terminate. This is likely due to some unflushed I/O.
+        if [ "${_variant}" = windows ]; then
+            taskkill /F /im mongod.exe || true
+        fi
 
   "run unit tests":
     command: shell.exec
@@ -478,10 +489,14 @@ functions:
         fi
 
         ${SCRIPT_DIR}/start-mongosqld.sh
+        ${SCRIPT_DIR}/ensure-mongosqld.sh
 
   "start mongodb":
     - command: shell.exec
       params:
+        # we need to start mongod in the background because it is causing non-termination
+        # of foreground shells on Windows, likely due to unflushed I/O.
+        background: true
         script: |
             ${PREPARE_SHELL}
             set -o errexit
@@ -489,6 +504,25 @@ functions:
                 export INFRASTRUCTURE_CONFIG="$INFRASTRUCTURE_CONFIG,mongo/version/${var_version}"
             fi
             ${SCRIPT_DIR}/start-mongodb.sh
+    - command: shell.exec
+      params:
+        script: |
+          # wait until mognod is up, since we are starting it in the background.
+          if [ "${_variant}" = windows ]; then
+              PS="ps -W | grep mongod | wc -l"
+          else
+              PS="ps aux | grep mongod | wc -l"
+          fi
+          i=0
+          while [ $(eval "$PS") = 0 ]; do
+              echo "waiting for mongod to start..."
+              i=$(expr $i + 1)
+              if [ $i = 20 ]; then
+                  echo "failed to start mongodb after 200 seconds"
+                  exit 1
+              fi
+              sleep 10
+          done
 
   "create sha1 user":
     - command: shell.exec
@@ -822,6 +856,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 302400  # 3.5 days
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
       vars:
         var_version: 3.6
@@ -841,6 +876,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 302400  # 3.5 days
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
       vars:
         var_version: 3.6
@@ -860,6 +896,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 302400  # 3.5 days
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
       vars:
         var_version: 3.6
@@ -879,6 +916,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 28800  # 8h
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
       vars:
         var_version: 4.0
@@ -898,6 +936,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 28800  # 8h
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
       vars:
         var_version: 3.6
@@ -917,6 +956,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 28800  # 8h
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
       vars:
         var_version: 3.4
@@ -936,6 +976,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 28800  # 8h
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
       vars:
         var_version: 3.2
@@ -955,6 +996,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 28800  # 8h
   commands:
+    - func: "install dependencies"
     - func: "build mongosqld"
     - func: "start mongodb"
       vars:
@@ -974,6 +1016,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 28800  # 8h
   commands:
+    - func: "install dependencies"
     - func: "build mongosqld"
     - func: "start mongodb"
       vars:
@@ -993,6 +1036,7 @@ tasks:
   tags: [ "benchmark" ]
   exec_timeout_secs: 28800  # 8h
   commands:
+    - func: "install dependencies"
     - func: "build mongosqld"
     - func: "start mongodb"
       vars:
@@ -1012,6 +1056,7 @@ tasks:
   exec_timeout_secs: 28800  # 8h
   tags: [ "benchmark" ]
   commands:
+    - func: "install dependencies"
     - func: "build mongosqld"
     - func: "start mongodb"
       vars:
@@ -1033,6 +1078,7 @@ tasks:
     - test
   exec_timeout_secs: 14400 # 4h
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -1047,6 +1093,7 @@ tasks:
     - nopushdown
   exec_timeout_secs: 14400 # 4h
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -1126,6 +1173,7 @@ tasks:
     - integration
     - test
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -1138,6 +1186,7 @@ tasks:
     - integration
     - test
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -1153,6 +1202,7 @@ tasks:
     - test
     - nopushdown
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -1168,6 +1218,7 @@ tasks:
     - integration
     - test
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -1180,6 +1231,7 @@ tasks:
     - integration
     - test
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -1193,6 +1245,7 @@ tasks:
     - test
     - nopushdown
   commands:
+    - func: "install dependencies"
     - func: "start mongodb"
     - func: "build mongosqld"
     - func: "start mongosqld"
@@ -2134,7 +2187,7 @@ axes:
   - id: windows
     display_name: Windows 64
     run_on:
-    - windows-64-vs2013-test
+    - windows-64-vs2019-large
     variables:
       _variant: windows
 
@@ -2518,7 +2571,7 @@ buildvariants:
   display_name: GSSAPI Auth Windows 64 (SSPI)
   expansions:
     _variant: windows
-  run_on: windows-64-vs2013-test
+  run_on: windows-64-vs2019-large
   tasks:
     - ".test .config .gssapi !.skip-windows"
 
